### ISSUE TITLE
pugme.herokuapp.com/bomb errors - crashes pugme script

### ISSUE THREAD

**Issue by jcurtis** [hubot-scripts/hubot-pugme#6]
http://pugme.herokuapp.com/bomb

![image](https://cloud.githubusercontent.com/assets/206295/15943976/c6647812-2e61-11e6-8fd9-0e2f83c9d843.png)

**Comment by StubbsPKS** [comment]
I also noticed this happening. I guess we need to figure out who maintains that heroku app and see if they can fix it.

**Comment by jcurtis** [comment]
If we could get a dump of all the pug urls in that database I don't think it would be a big deal to just hard code them into the repo.

**Comment by markmcintyre** [comment]
This is a tragedy. I second the call to just provide pug URLs in a json file included directly in the repo.

**Comment by anupdhml** [comment]
Looks like the heroku app is back again, but in case it's down again, here's a version based on reddit:
https://github.com/anupdhml/hubot-pugme-reddit/blob/master/src/pugme.coffee

Currently, it pulls pugs from top weekly posts in r/pugs.
